[package]
name = "tradar-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
tradar-core = { path = "../../tradar-core" }
tradar-connector-api = { path = "../../tradar-connector-api" }
tradar-query-workbench = { path = "../../tradar-query-workbench" }

async-trait = "0.1"
anyhow = "1"
futures-util = "0.3"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
testcontainers-modules = { version = "0.11", features = ["postgres"] }
