[workspace]
resolver = "3"
members = [
  "crates/tradar-core",
  "crates/tradar-connector-spi",
  "crates/tradar-query-workbench",
  "crates/tradar-connector-postgres",
  "crates/tradar-connector-sqlite",
  "crates/tradar-connector-elasticsearch",
  "crates/tradar-connector-redis",
  "crates/tradar-connector-mongo",
  "crates/tradar-connector-cassandra",
  "crates/tradar-connector-rabbitmq",
  "crates/tradar-connector-kafka",
  "crates/tradar-connector-http",
  "crates/tradar-app",
]
default-members = ["crates/tradar-app"]
