[workspace]
resolver = "3"
members = [
  "crates/tradar-core",
  "crates/tradar-connector-api",
  "crates/tradar-query-workbench",
  "crates/connectors/tradar-postgres",
  "crates/connectors/tradar-sqlite",
  "crates/connectors/tradar-elasticsearch",
  "crates/connectors/tradar-redis",
  "crates/connectors/tradar-mongo",
  "crates/connectors/tradar-cassandra",
  "crates/connectors/tradar-rabbitmq",
  "crates/connectors/tradar-kafka",
  "crates/tradar-app",
]
default-members = ["crates/tradar-app"]
