[package]
name = "tradar-cassandra"
version = "0.1.0"
edition = "2024"

[dependencies]
tradar-core = { path = "../../tradar-core" }
tradar-connector-api = { path = "../../tradar-connector-api" }
tradar-query-workbench = { path = "../../tradar-query-workbench" }

async-trait = "0.1"
anyhow = "1"
scylla = "1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
testcontainers = "0.23"
